trigger:
- main

resources:
- repo: self

variables:

  # Service Connection
  dockerRegistryServiceConnection: '2cdaa0c2-e958-487e-b0c3-ef797fddd487'

  # ACR Details
  imageRepository: 'tetrisgameapp'
  containerRegistry: 'mylab23.azurecr.io'

  # Dockerfile Path
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

  # Image Tag
  tag: '$(Build.BuildId)'

  # Agent Image
  vmImageName: 'ubuntu-latest'

stages:

# ==========================
# BUILD STAGE
# ==========================

- stage: Build
  displayName: Build and Push Docker Image

  jobs:

  - job: Build
    displayName: Build Job

    pool:
      vmImage: $(vmImageName)

    steps:

    # Build and Push Image
    - task: Docker@2
      displayName: Build and Push Docker Image

      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)

        tags: |
          $(tag)

# ==========================
# DEPLOY STAGE
# ==========================

- stage: Deploy
  displayName: Deploy to Azure Web App

  dependsOn: Build

  jobs:

  - job: Deploy
    displayName: Deploy Container

    pool:
      vmImage: $(vmImageName)

    steps:

    - task: AzureRmWebAppDeployment@5
      displayName: Deploy to Azure Web App

      inputs:
        ConnectionType: 'AzureRM'

        azureSubscription: 'Azure subscription 1(f3f6df71-2254-4c81-9ca2-9f96a3592ffa)'

        appType: 'webAppContainer'

        WebAppName: 'tetris-game-app'

        DockerNamespace: 'mylab23.azurecr.io'

        DockerRepository: 'tetrisgameapp'

        DockerImageTag: '$(tag)'